//! Blueprint actor: `new_blueprint_class.class`
//! Generated by PBGC. Do not hand-edit — changes will be overwritten.
//!
//! Component access goes through `pulsar_world_registry`'s dispatcher
//! against the LIVE world each `Actor` callback receives (#651) — there is
//! no private component store.

use pulsar_game::prelude::*;
use engine_class_derive::EngineClass;
#[allow(unused_imports)]
use pulsar_std::*;

// vars lives two levels up: <Class>::events::events → <Class>::events → <Class>
#[allow(unused_imports)]
use super::super::vars::*;

#[derive(EngineClass, Clone)]
pub struct NewBlueprintClass.class {}

impl NewBlueprintClass.class {
    pub fn new() -> Self { Self { } }
}

impl Default for NewBlueprintClass.class {
    fn default() -> Self { Self::new() }
}

impl NewBlueprintClass.class {
    /// Ensure every enabled prefab component exists on the actor's scene
    /// entity in the LIVE world (#651).
    ///
    /// Idempotent AND scene-respecting: hydration fires only when the class
    /// is absent, so per-instance values the scene already hydrated win over
    /// the defaults baked in at compile time. Classes without a live World
    /// registration are left to the JSON channel. Failures log and continue —
    /// one bad component never blocks the actor.
    pub fn __init_components(entity: Entity, world: &mut World) {
        if !pulsar_world_registry::world_component_present_for_class("LightComponent", world, entity) {
            if let Err(__e) = pulsar_world_registry::hydrate_world_component_for_class(
                "LightComponent",
                world,
                entity,
                &serde_json::from_str::<serde_json::Value>("{\"enabled\":true,\"affects_world\":true,\"light_type\":1,\"light_channels\":255,\"lighting_channel_0\":true,\"lighting_channel_1\":false,\"lighting_channel_2\":false,\"intensity\":1000.0,\"intensity_units\":1,\"exposure_compensation\":0.0,\"inverse_squared_falloff\":true,\"indirect_intensity\":1.0,\"max_draw_distance\":0.0,\"max_distance_fade_range\":0.0,\"color\":[1.0,0.0,0.8325047492980957,1.0],\"use_temperature\":false,\"temperature_kelvin\":6500.0,\"temperature_tint\":0.0,\"color_saturation\":1.0,\"color_contrast\":1.0,\"use_physical_light_color\":true,\"range\":1000.0,\"falloff_start\":0.0,\"attenuation_exponent\":2.0,\"source_radius\":0.0,\"source_length\":0.0,\"inner_cone_angle\":30.0,\"outer_cone_angle\":45.0,\"cast_shadows\":true,\"cast_static_shadows\":true,\"cast_dynamic_shadows\":true,\"cast_volumetric_shadow\":true,\"cast_contact_shadows\":false,\"shadow_bias\":0.5,\"shadow_normal_bias\":0.5,\"shadow_slope_bias\":0.5,\"shadow_filter_sharpen\":0.0,\"shadow_softness\":1.0,\"shadow_resolution_scale\":1.0,\"contact_shadow_non_shadow_casting_intensity\":0.0,\"affects_volumetric_fog\":true,\"volumetric_scattering_intensity\":1.0,\"volumetric_shadow_intensity\":1.0,\"fog_inscattering_intensity\":1.0,\"contact_shadow_length\":0.0,\"light_function_material\":\"\",\"light_function_scale\":[1.0,1.0,1.0],\"light_function_fade_distance\":0.0,\"light_function_disabled_brightness\":0.0,\"mobile_quality_level\":2,\"ray_tracing_inclusion\":true,\"virtual_shadow_map_enabled\":true,\"shadow_cache_mode\":0,\"per_view_visibility_mask\":65535,\"affects_translucency\":true,\"affects_reflections\":true,\"affects_global_illumination\":true,\"specular_scale\":1.0,\"diffuse_scale\":1.0}").unwrap_or_else(|_| serde_json::json!({})),
            ) {
                tracing::error!("blueprint `new_blueprint_class.class`: hydrating LightComponent failed: {__e}");
            }
        }
    }

    /// Call `begin_play` on each declared component class that implements it,
    /// through the same live-world dispatcher graph nodes use.
    pub fn __run_component_begin_plays(entity: Entity, world: &mut World) {
        if pulsar_reflection::REGISTRY.get_method("LightComponent", "begin_play").is_some() {
            if let Err(__e) = pulsar_world_registry::dispatch::invoke_component_method(
                world,
                entity,
                "LightComponent",
                0,
                "begin_play",
                vec![],
            ) {
                tracing::error!("blueprint `new_blueprint_class.class`: LightComponent::begin_play failed: {__e}");
            }
        }
    }
}


impl Actor for NewBlueprintClass.class {
    fn begin_play(&mut self, _entity: Entity, _world: &mut World) {
        Self::__init_components(_entity, _world);
        Self::__run_component_begin_plays(_entity, _world);
        logic::begin_play(_entity, _world);
    }

    // Signature MUST match the pinned `pulsar_scenedb::Actor` exactly.
    // `Actor::tick` is deliberately TIME-FREE there (see that trait's doc):
    // per-frame timing is the engine's concern and flows through ECS systems
    // and blueprint dispatch, never through this callback. Do not add
    // parameters here without changing SceneDB first — a mismatch is E0053 in
    // every generated project. Guarded by pulsar_game's
    // `blueprint_codegen_drift` compile probes (Pulsar-Native#652).
    fn tick(&mut self, _entity: Entity, _world: &mut World) {
        // No tick event in this blueprint.
    }
}

mod logic {
    // vars is three levels up inside this inline module:
    // logic → events::events → events → <Class> → vars
    #[allow(unused_imports)]
    use super::super::super::vars::*;
    #[allow(unused_imports)]
    use pulsar_std::*;

    // Auto-generated code from Pulsar Blueprint
    // DO NOT EDIT - Changes will be overwritten
    // Compiled with PBGC (Pulsar Blueprint Graph Compiler)


    pub fn begin_play(_entity: pulsar_game::Entity, _world: &mut pulsar_game::World) {
        if node_ccc658d7_b77c_4f6f_b300_f1a430b470b2_result { { let node_06888482_d7fa_43a1_88fd_0572dada0a7f_result = print_number (random_float ()) ; } }
    }

}
