//! Blueprint actor: `my_bp`
//! Generated by PBGC. Do not hand-edit — changes will be overwritten.

use engine_class_derive::EngineClass;
use pulsar_game::prelude::*;
#[allow(unused_imports)]
use pulsar_std::*;

// vars lives two levels up: <Class>::events::events → <Class>::events → <Class>
#[allow(unused_imports)]
use super::super::vars::*;

#[derive(EngineClass, Clone)]
pub struct MyBP {}

impl MyBP {
    pub fn new() -> Self {
        Self {}
    }
}

impl Default for MyBP {
    fn default() -> Self {
        Self::new()
    }
}

impl Actor for MyBP {
    fn begin_play(&mut self, _entity: Entity, _world: &mut World) {
        logic::begin_play();
    }

    fn tick(&mut self, _entity: Entity, _world: &mut World, _time: GameTime) {
        // No tick event in this blueprint.
    }
}

mod logic {
    // vars is three levels up inside this inline module:
    // logic → events::events → events → <Class> → vars
    #[allow(unused_imports)]
    use super::super::super::vars::*;
    #[allow(unused_imports)]
    use pulsar_std::*;

    // Auto-generated code from Pulsar Blueprint
    // DO NOT EDIT - Changes will be overwritten
    // Compiled with PBGC (Pulsar Blueprint Graph Compiler)

    // NOTE: Replace with actual pulsar_std import in production
    // use pulsar_std::*;

    pub fn begin_play() {
        {
            let node_a0bdff47_956d_4174_bd8b_b74fb1b8b2ab_result = print_number(0.0);
        }
        {
            let node_abbfaa66_9729_4fdd_bf1b_5bd471464ff2_result = print_number(0.0);
        }
        {
            let node_4429dec8_233f_4e50_95b9_77a2032dbf40_result = println(String::new());
        }
        {
            {
                {
                    let node_f3943088_1597_4a1c_8558_7a31a26b2c92_result =
                        print_formatted(String::new(), String::new(), String::new(), String::new());
                }
                {}
                {
                    let node_6b228e95_aba9_497f_b61d_d94e80465f88_result = print_bool(false);
                }
                {}
            }
            {
                let node_aef3fdca_6992_48a7_b16d_651ed2733547_result = print_number(0.0);
            }
            {}
            {}
        }
    }
}
