//! Blueprint actor: `my_bp`
//! Generated by PBGC. Do not hand-edit — changes will be overwritten.

use pulsar_game::prelude::*;
use engine_class_derive::EngineClass;

#[derive(Clone, EngineClass)]
pub struct MyBP {}

impl MyBP {
    pub fn new() -> Self { Self {} }
}

impl Default for MyBP {
    fn default() -> Self { Self::new() }
}

impl Actor for MyBP {
    fn begin_play(&mut self, _entity: Entity, _world: &mut World) {
        // No begin_play event in this blueprint.
    }

    fn tick(&mut self, _entity: Entity, _world: &mut World, _time: GameTime) {
        // No tick event in this blueprint.
    }
}

mod logic {
    // Auto-generated code from Pulsar Blueprint
    // DO NOT EDIT - Changes will be overwritten
    // Compiled with PBGC (Pulsar Blueprint Graph Compiler)

    // NOTE: Replace with actual pulsar_std import in production
    // use pulsar_std::*;


    pub fn main() {
        let node_072cc04c_7199_4cae_8a90_b82474db00f3_result = println(String::new());
    }

}
