//! Blueprint actor: `my_bp.class`
//! Generated by PBGC. Do not hand-edit — changes will be overwritten.

use pulsar_game::prelude::*;
use engine_class_derive::EngineClass;
#[allow(unused_imports)]
use pulsar_std::*;

// vars lives two levels up: <Class>::events::events → <Class>::events → <Class>
#[allow(unused_imports)]
use super::super::vars::*;

#[derive(EngineClass, Clone)]
pub struct MyBP.class {}

impl MyBP.class {
    pub fn new() -> Self { Self {} }
}

impl Default for MyBP.class {
    fn default() -> Self { Self::new() }
}

impl Actor for MyBP.class {
    fn begin_play(&mut self, _entity: Entity, _world: &mut World) {
        logic::begin_play();
    }

    fn tick(&mut self, _entity: Entity, _world: &mut World, _time: GameTime) {
        // No tick event in this blueprint.
    }
}

mod logic {
    // vars is three levels up inside this inline module:
    // logic → events::events → events → <Class> → vars
    #[allow(unused_imports)]
    use super::super::super::vars::*;
    #[allow(unused_imports)]
    use pulsar_std::*;

    // Auto-generated code from Pulsar Blueprint
    // DO NOT EDIT - Changes will be overwritten
    // Compiled with PBGC (Pulsar Blueprint Graph Compiler)


    pub fn begin_play() {
        let node_504ac3c6_fde7_4250_afd6_7576ebe50873_result = println(String::new());
    }

}
