//! engine_main — level bootstrap.  @generated-by-pulsar-engine_main
//!
//! This file is regenerated by the Pulsar editor whenever you compile a blueprint.
//! To prevent regeneration, remove the `@generated-by-pulsar-engine_main` marker.
//!
//! Native prefabs are controlled by `Pulsar/level.json`.
//! Gameplay script crates under `scripts/` are auto-discovered (#653).
//! Script classes run on placed class instances; global scripts are listed in
//! `Pulsar/scripting.json`.

use pulsar_game::prelude::*;

/// Set up the level: spawn native actors, register gameplay script crates and
/// enable the script driver.
///
/// Called once from `main()` before `game.run_blocking()`.
/// - Native actors + script-crate actors are registered into the tick loop's
///   shared world and receive `tick` every frame (via `register_actor`, which
///   also makes them hot-reload-safe in Play-In-Editor).
/// - The script driver runs one script instance per placed class instance
///   (and per global script); the `TickLoop` runs their events every frame.
pub fn setup(game: &mut TickLoop) -> Result<(), String> {
    // ── Native actors (from Pulsar/level.json) ────────────────────────────────
    // No native prefabs configured — add entries to Pulsar/level.json.

    // ── Gameplay script crates (scripts/) ──────────────────────────────
// Each crate registers its actors through TickLoop::register_actor,
// which stamps entity identities PIE hot reload re-binds to (#653).
    // User gameplay crate `scripts/test_scripts`:
    test_scripts::register_scripts(game)?;

    // ── Script classes (engine script VM) ─────────────────────────────────────
    //
    // The script driver follows the world: each placed class instance runs
    // its class's script (src/classes/*/events/.build/module.json) bound to
    // its object, from level load, Play-in-Editor placement or a script's
    // world::spawn. No instance is created here, and a level without class
    // instances runs no scripts. Global scripts: Pulsar/scripting.json.
    // Classes and settings come from the game's content (the project in
    // development, `Content/` when packaged), found at run time.
    game.enable_project_scripting()?;

    Ok(())
}
