//! engine_main — level bootstrap.  @generated-by-pulsar-engine_main
//!
//! This file is regenerated by the Pulsar editor whenever you compile a blueprint.
//! To prevent regeneration, remove the `@generated-by-pulsar-engine_main` marker.
//!
//! Native prefabs are controlled by `Pulsar/level.json`.
//! VM blueprints are auto-discovered from `src/classes/*/events/.build/bytecode.json`.

use pulsar_game::prelude::*;
use pulsar_game::blueprint_runtime::{BlueprintDispatcher, BlueprintEvent};
use std::sync::{Arc, Mutex};

/// Set up the level: spawn native actors and load VM-compiled blueprints.
///
/// Called once from `main()` before `game.run_blocking()`.
/// - Native actors are registered into `game.actors` and receive `tick` every frame.
/// - VM blueprints are loaded into `game.blueprint_dispatcher`; the `TickLoop`
///   dispatches `BlueprintEvent::Tick` to each instance after every frame.
pub fn setup(game: &mut TickLoop) -> Result<(), String> {
    // ── Native actors (from Pulsar/level.json) ────────────────────────────────
    // No native prefabs configured — add entries to Pulsar/level.json.

    // ── VM blueprint discovery ────────────────────────────────────────────────
    //
    // Scan src/classes/*/events/.build/bytecode.json.
    // Each file was written by the Blueprint Editor's BytecodeVm compile path.
    // The function-pointer slots are zero here; BlueprintDispatcher::new() calls
    // BpExecutor::prepare() which patches them from the embedded pulsar_std dylib.
    let classes_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("classes");

    if classes_dir.exists() {
        match BlueprintDispatcher::new() {
            Ok(mut dispatcher) => {
                let mut vm_loaded: usize = 0;

                let read_dir = std::fs::read_dir(&classes_dir)
                    .map_err(|e| format!("Cannot read classes dir: {e}"))?;

                for entry in read_dir.flatten() {
                    if !entry.path().is_dir() {
                        continue;
                    }

                    let build_path = entry
                        .path()
                        .join("events")
                        .join(".build")
                        .join("bytecode.json");

                    if !build_path.exists() {
                        continue;
                    }

                    let class_name = entry.file_name().to_string_lossy().into_owned();
                    // Each VM class gets a single default instance.
                    // For per-level multi-instance spawning, add support in level.json.
                    let object_id = format!("{class_name}__vm_default");

                    match dispatcher.register_instance(object_id.clone(), &build_path, None) {
                        Ok(()) => {
                            // Fire begin_play immediately so the blueprint can initialise state.
                            if let Err(e) = dispatcher.dispatch_event(
                                BlueprintEvent::BeginPlay { object_id: object_id.clone() }
                            ) {
                                tracing::warn!(
                                    "begin_play failed for VM blueprint '{class_name}': {e}"
                                );
                            }
                            vm_loaded += 1;
                            tracing::info!("VM blueprint loaded: {class_name} → {object_id}");
                        }
                        Err(e) => {
                            tracing::warn!(
                                "Failed to load VM blueprint '{class_name}': {e}"
                            );
                        }
                    }
                }

                if vm_loaded > 0 {
                    game.blueprint_dispatcher = Some(Arc::new(Mutex::new(dispatcher)));
                    tracing::info!(
                        "VM blueprint runtime active — {vm_loaded} class(es) loaded"
                    );
                } else {
                    tracing::debug!("No VM blueprints found in {}",  classes_dir.display());
                }
            }
            Err(e) => {
                // Non-fatal: native actors still run without the VM runtime.
                tracing::warn!("Could not initialise BlueprintDispatcher: {e}");
            }
        }
    }

    Ok(())
}
