//! Play-In-Editor embedding shim.  @generated-by-pulsar-embed-lib
//!
//! Regenerated by the Pulsar Core Project Builder. Exports the `pulsar_pie_*`
//! C-ABI symbols the editor loads when you press Play. Do not edit by hand —
//! remove the `@generated-by-pulsar-embed-lib` marker to opt out of regeneration.

use pulsar_game::embed;
use pulsar_pie_abi::{EngineContext, InputEvent, INIT_ERR, PIE_ABI_VERSION};

mod classes;
mod engine_main;

/// ABI revision this game was built against; the editor refuses to load on a
/// mismatch and asks the user to rebuild.
#[no_mangle]
pub extern "C" fn pulsar_pie_abi_version() -> u64 {
    PIE_ABI_VERSION
}

/// Build the embedded game: ECS world + offscreen Helio renderer on the editor's
/// GPU device. Returns `1` on success (and writes `ctx.out_texture`), `0` on
/// failure.
///
/// # Safety
/// `ctx` must point at a valid, host-populated `EngineContext`.
#[no_mangle]
pub unsafe extern "C" fn pulsar_pie_init(ctx: *mut EngineContext) -> u32 {
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| unsafe {
        embed::pie_init(ctx, engine_main::setup)
    }))
    .unwrap_or(INIT_ERR)
}

/// Advance simulation and render one frame into the offscreen target.
#[no_mangle]
pub extern "C" fn pulsar_pie_tick(delta_time: f32) {
    let _ = std::panic::catch_unwind(|| embed::pie_tick(delta_time));
}

/// Resize the offscreen render target.
#[no_mangle]
pub extern "C" fn pulsar_pie_resize(width: u32, height: u32) {
    let _ = std::panic::catch_unwind(|| embed::pie_resize(width, height));
}

/// Forward one input event from the editor's input abstraction.
///
/// # Safety
/// `ev` must be a valid pointer to an `InputEvent` for the duration of the call.
#[no_mangle]
pub unsafe extern "C" fn pulsar_pie_input(ev: *const InputEvent) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| unsafe {
        embed::pie_input(ev)
    }));
}

/// Tear down the embedded game before the editor unloads the library.
#[no_mangle]
pub extern "C" fn pulsar_pie_shutdown() {
    let _ = std::panic::catch_unwind(embed::pie_shutdown);
}

/// An asset was updated in the editor (e.g. a class was saved): reload it.
///
/// # Safety
/// Each pointer/length pair must be a valid UTF-8 range or null.
#[no_mangle]
pub unsafe extern "C" fn pulsar_pie_asset_updated(
    kind: *const u8,
    kind_len: usize,
    id: *const u8,
    id_len: usize,
    path: *const u8,
    path_len: usize,
) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| unsafe {
        embed::pie_asset_updated(kind, kind_len, id, id_len, path, path_len)
    }));
}

/// The session's event debug snapshot (JSON) for the editor's events panel.
///
/// # Safety
/// `out` must be valid for `capacity` bytes of writes (or `capacity` 0).
#[no_mangle]
pub unsafe extern "C" fn pulsar_pie_events_snapshot(out: *mut u8, capacity: usize) -> usize {
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| unsafe {
        embed::pie_events_snapshot(out, capacity)
    }))
    .unwrap_or(0)
}

/// Simulation control for the editor's pause / step buttons.
#[no_mangle]
pub extern "C" fn pulsar_pie_control(command: u32, arg: u64) -> u64 {
    std::panic::catch_unwind(|| embed::pie_control(command, arg)).unwrap_or(0)
}

/// Script problems raised since the last call (JSON) for the problems panel.
///
/// # Safety
/// `out` must be valid for `capacity` bytes of writes (or `capacity` 0).
#[no_mangle]
pub unsafe extern "C" fn pulsar_pie_take_problems(out: *mut u8, capacity: usize) -> usize {
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| unsafe {
        embed::pie_take_problems(out, capacity)
    }))
    .unwrap_or(0)
}

/// The session's event hub for editor plugins (a Gamma `RawBus`).
///
/// # Safety
/// `out` must be valid for `out_size` bytes of writes.
#[no_mangle]
pub unsafe extern "C" fn pulsar_pie_event_bus(out: *mut std::ffi::c_void, out_size: usize) -> u32 {
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| unsafe {
        embed::pie_event_bus(out, out_size)
    }))
    .unwrap_or(0)
}
