//! blank_project — generated by Pulsar Core Project Builder.

use pulsar_game::prelude::*;

mod classes;
mod engine_main;

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(std::env::var("RUST_LOG").unwrap_or_else(|_| "info".into()))
        .init();

    tracing::info!("Starting {}", env!("CARGO_PKG_NAME"));

    engine_main::main();

    let threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4);

    let mut game = TickLoop::new(TickMode::default(), threads);

    tracing::info!("World ready — entering tick loop");
    game.run_blocking();
}
