//! Test — generated by Pulsar Core Project Builder.
//!
//! Nothing about where the project lives is compiled in: at start-up the
//! game finds its content (`pulsar_game::standalone`) in `Content/` next to
//! the executable when packaged (`pulsar package`), otherwise in the
//! project around the executable (`cargo run`). Options:
//! `--headless --frames N` runs the game loop without a window,
//! `--content DIR` reads content from DIR.

mod classes;
mod engine_main;

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(std::env::var("RUST_LOG").unwrap_or_else(|_| "info".into()))
        .init();

    tracing::info!("Starting {}", env!("CARGO_PKG_NAME"));

    // Content discovery, `engine_main::setup`, then the window (or a
    // headless run). The startup level and window come from
    // `Pulsar/project.json`.
    std::process::exit(pulsar_game::standalone::run(engine_main::setup));
}
