//! Blueprint actor: `example_class`
//! Generated by PBGC. Do not hand-edit — changes will be overwritten.

use pulsar_game::prelude::*;
use engine_class_derive::EngineClass;

#[derive(Clone, EngineClass)]
pub struct ExampleClass {}

impl ExampleClass {
    pub fn new() -> Self { Self {} }
}

impl Default for ExampleClass {
    fn default() -> Self { Self::new() }
}

impl Actor for ExampleClass {
    fn begin_play(&mut self, _entity: Entity, _world: &mut World) {
        logic::begin_play();
    }

    fn tick(&mut self, _entity: Entity, _world: &mut World, _time: GameTime) {
        // No tick event in this blueprint.
    }
}

mod logic {
    // Auto-generated code from Pulsar Blueprint
    // DO NOT EDIT - Changes will be overwritten
    // Compiled with PBGC (Pulsar Blueprint Graph Compiler)

    // NOTE: Replace with actual pulsar_std import in production
    // use pulsar_std::*;


    pub fn main() {
        DSFASDF.with(|v| *v.borrow_mut() = DSFASDF.with(|v| v.borrow().clone()));
        if node_dcf02495_0e52_439e_8e2d_8c0d69a86ff9_result { let node_print_true_result = print_string ("Result is greater than 3! \u{2713}") ; } else { let node_print_false_result = print_string ("Result is 3 or less. \u{2717}") ; }
    }

    pub fn begin_play() {
        let lua_runtime = Lua :: new () ; let output : Result < String > = lua_runtime . load (templateLua ()) . eval () ; return output . unwrap () ;
    }

}
